# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
  - name: gcr.io/k8s-skaffold/skaffold:v2.14.1
    args:
      - "skaffold"
      - "build"
      - "--file-output=/workspace/artifacts.json"
      - "--default-repo=$_CONTAINER_REGISTRY"
  - id: 'create-attestation-emailservice'
    name: '$_BINARY_AUTH_IMAGE'
    args:
      - '--artifact-url'
      - '$_CONTAINER_REGISTRY/emailservice:latest'
      - '--attestor'
      - '$_ATTESTOR_ID'
      - '--keyversion'
      - '$_KMS_KEY_VERSION'
  - id: 'create-attestation-productcatalogservice'
    name: '$_BINARY_AUTH_IMAGE'
    args:
      - '--artifact-url'
      - '$_CONTAINER_REGISTRY/productcatalogservice:latest'
      - '--attestor'
      - '$_ATTESTOR_ID'
      - '--keyversion'
      - '$_KMS_KEY_VERSION'
  - id: 'create-attestation-recommendationservice'
    name: '$_BINARY_AUTH_IMAGE'
    args:
      - '--artifact-url'
      - '$_CONTAINER_REGISTRY/recommendationservice:latest'
      - '--attestor'
      - '$_ATTESTOR_ID'
      - '--keyversion'
      - '$_KMS_KEY_VERSION'
  - id: 'create-attestation-shoppingassistantservice'
    name: '$_BINARY_AUTH_IMAGE'
    args:
      - '--artifact-url'
      - '$_CONTAINER_REGISTRY/shoppingassistantservice:latest'
      - '--attestor'
      - '$_ATTESTOR_ID'
      - '--keyversion'
      - '$_KMS_KEY_VERSION'
  - id: 'create-attestation-shippingservice'
    name: '$_BINARY_AUTH_IMAGE'
    args:
      - '--artifact-url'
      - '$_CONTAINER_REGISTRY/shippingservice:latest'
      - '--attestor'
      - '$_ATTESTOR_ID'
      - '--keyversion'
      - '$_KMS_KEY_VERSION'
  - id: 'create-attestation-checkoutservice'
    name: '$_BINARY_AUTH_IMAGE'
    args:
      - '--artifact-url'
      - '$_CONTAINER_REGISTRY/checkoutservice:latest'
      - '--attestor'
      - '$_ATTESTOR_ID'
      - '--keyversion'
      - '$_KMS_KEY_VERSION'
  - id: 'create-attestation-paymentservice'
    name: '$_BINARY_AUTH_IMAGE'
    args:
      - '--artifact-url'
      - '$_CONTAINER_REGISTRY/paymentservice:latest'
      - '--attestor'
      - '$_ATTESTOR_ID'
      - '--keyversion'
      - '$_KMS_KEY_VERSION'
  - id: 'create-attestation-currencyservice'
    name: '$_BINARY_AUTH_IMAGE'
    args:
      - '--artifact-url'
      - '$_CONTAINER_REGISTRY/currencyservice:latest'
      - '--attestor'
      - '$_ATTESTOR_ID'
      - '--keyversion'
      - '$_KMS_KEY_VERSION'
  - id: 'create-attestation-cartservice'
    name: '$_BINARY_AUTH_IMAGE'
    args:
      - '--artifact-url'
      - '$_CONTAINER_REGISTRY/cartservice:latest'
      - '--attestor'
      - '$_ATTESTOR_ID'
      - '--keyversion'
      - '$_KMS_KEY_VERSION'
  - id: 'create-attestation-frontend'
    name: '$_BINARY_AUTH_IMAGE'
    args:
      - '--artifact-url'
      - '$_CONTAINER_REGISTRY/frontend:latest'
      - '--attestor'
      - '$_ATTESTOR_ID'
      - '--keyversion'
      - '$_KMS_KEY_VERSION'
  - name: gcr.io/cloud-builders/gcloud
    args:
      - "deploy"
      - "releases"
      - "create"
      - "cymbalshop-$SHORT_SHA"
      - "--delivery-pipeline=$_CLOUDDEPLOY_PIPELINE_NAME"
      - "--build-artifacts=/workspace/artifacts.json"
      - "--gcs-source-staging-dir=$_SOURCE_STAGING_BUCKET/$SHORT_SHA"
      - "--skaffold-file=skaffold.yaml"
      - "--region=$LOCATION"
options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: '${_PRIVATE_POOL}'
