#!/usr/bin/env python3
# Copyright 2024 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#  Copyright 2023 Google LLC
#
#  Licensed under the Apache License, Version 2.0 (the "License");
#  you may not use this file except in compliance with the License.
#  You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS,
#  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#  See the License for the specific language governing permissions and
#  limitations under the License.

"""
Download MC simulation data in secured environment and upload to bucket
"""


import yfinance as yf

from google.cloud import storage
from absl import app
from absl import flags
from datetime import datetime
from datetime import timedelta

FLAGS = flags.FLAGS


flags.DEFINE_string("bucket_name", None, "Bucket where ticker data is located")
flags.DEFINE_list(
    "ticker_list", "ADM,ADP,ADRNY,ADSK,ADYEY,ADYYF,AEDFF,AEE,AEG,AEGOF,AEP,AES,AEXAF,AEXAY,AFL,AGESF,AGESY,AGPPF,AHODF,AHT,AIAGF,AIAGY,AIG,AIIXY,AIQUF,AIQUY,AIXXF,AIZ,AJG,AKAM,AKZOF,AKZOY,ALB,ALC,ALFVF,ALFVY,ALGN,ALIZF,ALIZY,ALK,ALL,ALLE,ALV,AMADF,AMADY,AMAT,AMCCF,AMD,AME,AMGN,AMIGF,AMIGY,AMP,AMSYF,AMT,AMZN,ANET,ANFGF,ANIOY,ANNSF,ANSS,AON,AOS,APA,APD,APEMY,APH,APTV,AARGNF,ARGX,ASAZF,ASAZY,ASBFF,ASBFY,ASHTF,ASHTY,ASML,ASMLF,ATDRF,ATDRY,ATLCY,ATLKY,ATLPF,ATO,ATOGF,ATRRF,AVB,AVGO,AVHNF,AVHNY,AVVIY,AVY,AWK,AXAHF,AXAHY,AXP,AZN,AZNCF,AZO,BA,BABWF,BAC,BAESY,BALL,BALY,BASFY,BAX,BAYRY,BAYZF,BBVA,BBVXF,BBY,BCDRF,BCLYF,BBDNNY,BDRFF,BDRFY,BDX,BECTY,BEN,BESIY,BESVF,BF-B,BFFAF,BFLBF,BFLBY,BGAOF,BGAOY,BHTLF,BIDU,BIIB,BK,BKGFF,BKGFY,BKIMF,BKNG,BKNIY,BLK,BMRRY,BMWYY,BMY,BMYMP,BNDSF,BNDSY,BNPQF,BNPQY,BNTGF,BNTGY,BOSSY,BOUYF,BP,BPAQF,BR,BRK-B,BRLAF,BSX,BTAFF,BTDPF,BTDPY,BTGOF,BTI,BTLCY,BUD,BUDFF,BURBY,BWA,BXP,BZLFF,BZLFY,C,CAG,CAH,CAIXY,CAPMF,CAT,CB,CBRE,CCCMF,CCHBF,CCHGY,CCI,CCL,CDMGF,CDNS,CE,CEG,CEVMF,CEVMY,CF,CFG,CFMOF,CFRHF,CFRUY,CGEMY,CGUIF,CHD,CHRW,CHTR,CI,CINF,CL,CLLNY,CLNXF,CLX,CMA,CMCSA,CME,CMG,CMI,CMPGF,CMPGY,CMPUY,CMPVF,CMS,CMS-PB,CNC,CNP,CODGF,CODYY,COF,COIHF,COIHY,COO,COP,COST,COVTY,CPB,CPRT,CPYYF,CPYYY,CRARF,CRERF,CRH,CRM,CRRFY,CRZBF,CRZBY,CS,CSCO,CSX,CTAS,CTSH,CTTAF,CTTAY,CTVA,CUK,CUKPF,CUYTY,CVS,CVVTF,CVX,CYJBF,CYJBY,CZMWF,CZMWY,D,DAL,DANOY,DASTY,DB,DBOEY,DCCPF,DD,DE,DEO,DEUZF,DFS,DG,DGEAF,DGWPF,DGX,DHI,DHLGY,DHR,DIS,DITHF,DLAKF,DLAKY,DLR,DLTR,DLVHF,DMPHF,DOV,DOW,DPUKY,DRI,DRKTF,DTCWY,DTE,DTEGF,DTEGY,DTRUY,DUAVF,DUERF,DUK,DVA,DVN,DWHHF,DXC,EA,EADSF,EADSY,EAPIF,EBAY,ECL,ED,EDVMF,EENEF,EFX,EIPAF,EIX,EL,ELEZF,ELEZY,ELMUF,ELMUY,ELORY,ELROF,EMN,EMR,ENAKF,ENGIY,EOG,EONGY,EQIX,ERFSF,ERIC,ERIXF,ES,ESGRO,ESLOF,ESLOY,ESS,ETCMY,ETN,ETR,ETTYF,EUZOF,EVKIF,EVKIY,EVO,EVOTF,EVRG,EW,EXC,EXPD,EXPE,EXPGF,EXPGY,EXR,F,FANG,FAST,FCX,FDX,FE,FFIV,FI,FIS,FITB,FLMNF,FLMNY,FLUIF,FMC,FMCQF,FMS,FNCDY,FNCTF,FNLPF,FNNTF,FOJCF,FOJCY,FOX,FPRUF,FPRUY,FRCB,FRTAF,FRTAY,FSNUF,FSNUY,FTNT,FTV,FUPBY,FUPEF,FUPPF,FXBY,GASNF,GASNY,GBERF,GBERY,GBLBF,GBLBY,GE,GEAGF,GIFLF,GIFOF,GIKLY,GILD,GIS,GKSGF,GLAXF,GLNCY,GLPG,GLPGF,GLW,GM,GMVHF,GMVHY,GNGBF,GNGBY,GOOG,GOOGL,GPC,GPDNF,GPN,GRDDY,GRFS,GRMN,GRNNF,GRRMY,GS,GS-PK,GSK,GVDBF,GVDNY,GWW,GZPZF,GZPZY,HAGHY,HAL,HALMY,HAS,HBAN,HBBHF,HBCYF,HBGRY,HBRIY,HCA,HCMLY,HCP,HD,HDELY,HEINY,HENKY,HES,HESAY,HIG,HII,HINKF,HLBZF,HLFFF,HLKHF,HLLGY,HLMAF,HLN,HLT,HMRZF,HNNMY,HNSDF,HOCFF,HOLX,HON,HOYFF,HPE,HPQ,HRGLF,HRGLY,HRL,HSBC,HSIC,HST,HSY,HUGPF,HUM,HVRRY,HWDJF,HXGBF,HXGBY,HYPOF,IBDRY,IBM,ICAGY,ICE,ICGUF,ICHGF,IDEXF,IDXX,IFF,IFJPY,IFNNF,IFNNY,IFPJF,IHG,IKTSF,IKTSY,ILMN,IMBBF,IMBBY,IMCDY,IMDZF,IMQCF,IMYSF,IMYSY,INCY,INDHF,ING,INGVF,INPAP,INRLF,INTC,INTU,IP,IPG,IPSOF,IQV,IRM,ISMAF,ISMAY,ISNPY,ISRG,IT,ITW,IVSBF,IVSXF,IVZ,J,JBHT,JCDXY,JCI,JD,JDCMF,JDDSF,JDSPY,JGHAF,JGHHY,JKHY,JNJ,JNPKF,JNPR,JPM,JSAIY,JSNSF,K,KBCSF,KBCSY,KDP,KDSKF,KEYS,KGFHF,KGFHY,KHC,KIGRY,KIM,KKOYF,KKOYY,KKPNF,KKPNY,KLAC,KLKNF,KMB,KMI,KMX,KNBHF,KNCRF,KNCRY,KNKZF,KNNGF,KNRRY,KNYJF,KNYJY,KO,KOJAF,KOYJF,KPLUF,KPLUY,KR,KRNNF,KRNTY,L,LEGIF,LEN,LGGNF,LGGNY,LGRDY,LGRVF,LH,LIN,LKQ,LLDTF,LLY,LNC,LNSTY,LNT,LNXSF,LNXSY,LOW,LRCX,LRLCF,LUKOY,LUV,LVMHF,LW,LYB,LYG,LZAGF,LZAGY,MA,MAA,MAR,MAS,MBGAF,MBISF,MCD,MCHP,MCK,MCO,MDLZ,MDT,MET,MGDDF,MGM,MGNI,MHK,MKC,MKGAF,MKKGY,MLM,MLSPF,MLXSF,MMC,MMM,MNST,MO,MONDY,MOS,MPC,MPFRF,MPFRY,MPHYF,MPSYF,MRO,MRPRF,MRVL,MS,MSCI,MSFT,MMT,MTAGF,MTB,MTD,MTTRY,MTTWF,MTUAF,MTUAY,MU,MURGY,MWRK,NCLH,NDAQ,NEE,NEEXU,NEM,NEMKY,NEMTF,NESN,NETTF,NEXNY,NFLX,NGG,NGGTF,NGLOY,NGRRF,NI,NKE,NKRKF,NKRKY,NNGPF,NNGRY,NNXXY,NOEJF,NOK,NOKBF,NPACF,NRDBY,NRDXF,NRG,NRXXY,NSRGY,NTAP,NTES,NTOIY,NTRS,NUE,NVDA,NVS,NVSEF,NWG,NWL,NWS,NWSA,NXGPF,NXGPY,NXPI,O,OAOFY,OCDDY,OCDGF,OCLCF,OEC,OKE,OKTA,OMC,ORAN,ORCL,ORINF,ORINY,ORLY,ORPEF,OUKPF,OUKPY,OUTFF,OUTKY,OXY,PARA,PASTF,PAYX,PBBGF,PBSFF,PBSFY,PCAR,PDD,PDRDF,PEG,PFE,PFFVF,PG,PGPEF,PGR,PH,PHG,PHM,PHPPY,PLD,PLDGP,PM,PMMAF,PMOIF,PNC,PNR,PNW,PNXGF,POAHY,POYYF,PPG,PPL,PPRUF,PPRUY,PRNDY,PRU,PSA,PSHZF,PSMMF,PSMMY,PSO,PSORF,PSX,PUBGY,PUK,PUKPF,PUMSY,PWR,PYPL,QCOM,QGEN,QRVO,RANJF,RANJY,RATIY,RBGLY,RBSPF,RCL,RDEIF,RE,REGN,RELX,REPYF,REPYY,RF,RGLXY,RHHBY,RHHVF,RHI,RJF,RKLIF,RL,RLXXF,RMD,RNLSY,RNMBF,RNMBY,RNSDF,ROK,ROL,ROP,ROST,ROSYY,RSG,RSMDF,RTLLF,RTMVY,RTO,RTX,RUBSF,RWEOY,RYCEF,RYCEY,RYDAF,RYLPF,SAEYY,SAFRF,SAFRY,SAN,SAP,SAPGF,SARTF,SAXPF,SAXPY,SBAC,SBGSF,SBGSY,SBUX,SCABY,SCBFF,SCBFY,SCCTY,SCFLF,SCGLF,SCHW,SCMWY,SCOTF,SCRYY,SCTBF,SCTBY,SDVKF,SDVKY,SEE,SEGXF,SEOAY,SEOJF,SFFLY,SFFYF,SFHLF,SFNXF,SFQ,SGEN,SGGEF,SGLFF,SGPYY,SHNWF,SHPPF,SHW,SIEGY,SIRI,SIUAF,SIXGF,SJM,SKBSY,SKFOF,SKSBF,SKUFF,SLB,SLOIY,SLUNF,SLVYY,SMAWF,SMEGF,SMFTF,SMGKF,SMGZY,SMIZF,SMMNY,SMNEY,SMTGF,SMTGY,SNA,SNN,SNNUF,SNPS,SNY,SNYNF,SO,SOBS,SPG,SPGI,SPSAF,SPXSF,SRE,SSEZY,SSLLF,SSSGY,STE,STJPF,STM,STMEF,STMZF,STRNY,STT,STWRY,STX,STZ,SUVPF,SVCBF,SVJTY,SVKEF,SVNLF,SVNLY,SVTRF,SVYSF,SWDAF,SWDBF,SWDBY,SWK,SWKS,SWMAF,SWMAY,SWSDF,SWZCF,SXT,SXYAY,SYF,SYIEF,SYIEY,SYK,SYY,SZGPY,SZLMY,T,TAGOF,TAGYY,TAP-A,TDG,TEF,TEL,TELDF,TFX,TGNOF,TGOPF,TGOPY,TGT,THLEF,THNPF,THNPY,TJX,TKAMY,TLLXY,TLPFF,TLPFY,TLSNF,TLSNY,TLTZF,TLTZY,TMO,TMUS,TMVWY,TNXXF,TOT,TPLKF,TPR,TROW,TRV,TSCDF,TSCDY,TSCO,TSLA,TSN,TTE,TTFNF,TTWO,TWODF,TWODY,TWTR,TXN,TYEKF,UAL,UBS,UCBJF,UCBJY,UDIRF,UDR,UHID,UHS,UHT,UL,ULTA,UN,UNBLF,UNH,UNIRF,UNLYF,UNP,UNPRF,UNRIF,UNVGY,UPMKF,UPMMY,UPS,URI,USB,UUGRY,V,VARGF,VARTY,VCISF,VCISY,VEOEY,VFC,VGPBF,VIVEF,VIVHY,VLKAF,VLMTY,VLO,VLOUF,VLOWY,VMC,VNNVF,VNO,VNORP,VOD,VODPF,VONOY,VOYJF,VRSK,VRSN,VRTX,VTAGY,VTR,VTSCY,VTWRF,VWAGY,VZ,WAB,WAT,WBA,WDC,WEC,WELL,WFC,WHR,WKCMF,WKRCF,WLTW,WM,WMB,WMT,WP,WPP,WPPGF,WRDLY,WRK,WTBCF,WTBDY,WTKWY,WTW,WWLNF,WY,WYNN,XINXF,XOM,XON,XRAY,XYL,YNDX,YUM,ZBH,ZFSVF,ZION,ZLDSF,ZLNDY,ZLPSF,ZM,ZOPLY,ZTS,ZURVY", "List of Stock Ticker to run"
)
flags.DEFINE_string(
    "start_date", "2022-01-01", "Start data for data query, default 2022-01-01"
)
flags.DEFINE_integer(
    "calendar_days", 365, "How many calendar days to include in the calculation"
)

flags.mark_flag_as_required("bucket_name")


def get_historical_data_yahoo(ticker, start_date, end_date):
    # get historical market data: https://pypi.org/project/yfinance/
    raw_data = yf.Ticker(ticker).history(start=start_date, end=end_date)    
    bucket_name = FLAGS.bucket_name
    client = storage.Client()
    bucket = client.bucket(bucket_name)
    blob = bucket.blob(f"{ticker}_{start_date}_{end_date}.csv")
    csv = raw_data.to_csv()
    blob.upload_from_string(csv)
    print(f"Uploaded {len(csv)} bytes succesfully.")
    return raw_data

def main(argv):
    start_date = FLAGS.start_date
    end_date = f'{(datetime.strptime(FLAGS.start_date,"%Y-%m-%d") + timedelta(days = FLAGS.calendar_days)).date()}'
    for ticker in FLAGS.ticker_list:
        print(f"Downloading data for '{ticker}'")
        get_historical_data_yahoo(ticker, start_date, end_date)


if __name__ == "__main__":
    """ This is executed when run from the command line """
    app.run(main)
